---
title: "Adi Diferansiyel Denklemler"
---

## Adi Diferansiyel Denklemler

Aşağıdaki gibi bir adet diferansiyel denklem veya denklem sistemimiz olsun.

$$
\begin{equation}
    \frac{d}{dx}y(x) = F(x,y)
\end{equation}
$$

- Bu denklemi çözmek demek sağ ve sol tarafın integralini almak demektir.
- Bu denklemi çözmek demek *sayısal* olarak $y(x)$ fonksiyonunu bulmak demektir. Yani istenilen bir x değeri için $y(x)$ fonksiyonunun değerini elde ederiz.
- $y(x)$ ve $F(x,y)$ birer vektör olabilir. Örneğin $\vec{y}(x) = (y_{1}(x), y_{2}(x))$.
- İkinci dereceden diferansiyel denklemleri çözmek için denklemi iki adet birinci dereceden diferansiyel denkleme indirgeme yapmamız gerekmektedir.

$$
\begin{align*}
    \frac{d^{2}}{dx^{2}}y(x) =& F(x,y)\\
    \frac{d}{dx}y(x) =& v(x,y) \qquad \text{ve} \qquad \frac{d}{dx}v(x) = F(x,y)
\end{align*}
$$

1. Çözüme başlamak için fonksiyonun başlangıçtaki değerine ihtiyacınız vardır; **Başlangıç Değer Problemi, BDP (IVP)**
2. Çözümün sınırlarında hangi değerler aldığını bilerek de fonksiyonu elde edebiliriz; **Sınır Değer Problemi, SDP (BVP)**

### Örnek

- Başlangıç değer problemi:

$$
y''(x)= -y, \qquad y(0)=1, \qquad y'(0)=0 \text{.}
$$

- Sınır değer problemi:

$$
y''(x)= -y, \qquad y(0)=1, \qquad y'(\pi)=0 \text{.}
$$
