project:
  type: website
  output-dir: _site
  preview:
    browser: true

execute:
  freeze: auto

website:
  title: "Bilgisayarlı Yöntemler"
  favicon: "resimler/favicon.png"
  reader-mode: true
  page-navigation: true
  site-url: "https://bulmust.github.io/bilgisayarli-yontemler"
  repo-url: https://github.com/bulmust/bilgisayarli-yontemler
  repo-actions: [edit, issue]
  page-footer:
    left: |
      This website is built with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=80px}](https://quarto.org/).
    right: "&copy; Copyright 2024, Taygun Bulmus"
  sidebar: 
    logo: "resimler/logo.png"
    pinned: false
    alignment: center
    border: true
    collapse-level: 3
    tools:
      - icon: github
        href: https://github.com/bulmust/bilgisayarli-yontemler
      - icon: file-person
        href: https://bulmust.github.io/
    contents:
      - section: "**İçerik**"
        contents:
          - href: icerik/izlence.qmd
          - href: icerik/bilYonMod.qmd
      - section: "**Konular**"
        contents:
          - section: Adi Diferansiyel Denklemler
            href: icerik/konular/adi-diferansiyel-denklemler.qmd
            contents:
              - icerik/konular/adi-diferansiyel-denklemler/bdp-giris.qmd
              - icerik/konular/adi-diferansiyel-denklemler/bdp-euler-yontemi.qmd
              - icerik/konular/adi-diferansiyel-denklemler/bdp-denklem-sistemleri.qmd
              - icerik/konular/adi-diferansiyel-denklemler/bdp-ikinci-dereceden-diferansiyel-denklemler.qmd
              - icerik/konular/adi-diferansiyel-denklemler/bdp-runge-kutta-yontemleri.qmd
              - icerik/konular/adi-diferansiyel-denklemler/sdp-giris.qmd
              - icerik/konular/adi-diferansiyel-denklemler/sdp-atis-yontemi.qmd
              - icerik/konular/adi-diferansiyel-denklemler/sdp-sonlu-farklar-yontemi.qmd
          - section: Fourier Analizi
            href: icerik/konular/fourier-analizi.qmd
            contents:
              - icerik/konular/fourier-analizi/giris.qmd
              - icerik/konular/fourier-analizi/kfd-kesikli-fourier-donusumu.qmd
              - icerik/konular/fourier-analizi/hfd-hizli-fourier-donusumu.qmd
              - icerik/konular/fourier-analizi/thfd-ters-hizli-fourier-donusumu.qmd
              - icerik/konular/fourier-analizi/uygulama-ses-dalgalari.qmd
          - section: Veri Analizi
            href: icerik/konular/veri-analizi.qmd
            contents:
              - icerik/konular/veri-analizi/pandas-giris.qmd
              - icerik/konular/veri-analizi/pandas-veri-manipülasyonu.qmd
              - icerik/konular/veri-analizi/pandas-uygulama.qmd
          - section: İstatistik
            href: icerik/konular/istatistik.qmd
            contents:
              - icerik/konular/istatistik/temel-kavramlar.qmd
              - icerik/konular/istatistik/uygulama-thinkstat2.qmd
              - icerik/konular/istatistik/olasilik-kutle-fonksiyonu.qmd
              - icerik/konular/istatistik/kumulatif-dagilim-fonksiyonu.qmd
              - icerik/konular/istatistik/dagilimlarin-modellenmesi.qmd

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    author: "Taygun Bulmus"
    toc: true
    toc-expand: true
    toc-title: "**Bu sayfada**"
    highlight-style: github
    code-copy: true
    code-overflow: scroll
    code-fold: false
    code-line-numbers: true
    code-link: true
    code-links:
      - text: bilYonMod.py
        icon: file-code
        href: moduller/bilYonMod.py

date: last-modified
lang: "tr"
bibliography: "bib/bilgisayarli-yontemler.bib"
csl: "bib/american-physics-society.csl"