---
title: "İstatistik - Uygulamalar"
---

Bu bölümde thinkstats2 kitabındaki bazı alıştırmaları çözeceğiz.

Thinkstats2 kitabına şu linkten ulaşabilirsiniz: <https://greenteapress.com/thinkstats2/thinkstats2.pdf>

Uygulamaları ise github sayfasından ulaşabilirsiniz. <https://github.com/AllenDowney/ThinkStats2>

## İstatistiksel Bakış Açısı

> Anekdot: "İlk çocuklar için hamilelik süresi daha uzundur."

- **Data Toplama (Data collection)**: Amerikan toplumu için çocuk doğum yaş verisini toplayalım.
- **Açıklayıcı İstatistikler (Descriptive Statistics)**: Veriyi temel olarak açıklayan istatistiksel kavramlara bakalım.
- **Veri Analizi Açıklama (Exploratory Data Analysis)**: Veriyi daha iyi anlamak için tekrarlara, farklılıklara veya diğer özelliklere bakalım.
- **Tahmin (Estimation)**: Veriye göre bir model kuralım ve genel nüfus hakkında tahminde bulunalım.
- **Hipotez Testi (Hypothesis Testing)**: Açığa çıkan etkileri, örneğin iki grup arasındaki farkı test edelim. Bu etkilerin olma olasılıklarını hesaplayalım.

## Amerika Aile Büyüme Oranları

- Veri'nin alındığı site: [National Survey of Family Growth (NSFG)](http://cdc.gov/nchs/nsfg.htm)
- Kullanacağımız veri, bir örneklem alarak yani Amerika'daki nüfusun bir kısmını seçerek elde edilmiş veridir.
- *Cycle 6* verisi kullanılacaktır. Burada cycle kelimesi sürekli alınan bir çalışmadaki her bir örneklem anlamına gelir. Bu çalışmadaki toplanan veri Ocak 2002- Mart 2003 yılları arasında alınmıştır.
- **Amacımız**: Amerika'daki annelerin hamilelik sürelerine bakacağız. **İlk kez doğum yapan annelerin hamilelik süreleri daha uzun mu daha kısa mı belirleyeceğiz.**
- **Kodkitabı** (codebook): [NSFG6 Codebook](https://www.cdc.gov/nchs/nsfg/nsfg_cycle6.htm)

## Veriyi İçeri aktarma

- [veri/veri_thinkStats2_2002FemPreg.dat.gz](../../../veri/veri_thinkStats2_2002FemPreg.dat.gz) dosyası sıkıştırılmış, hamilelik veri dosyasıdır. *Her bir satıra kayıt (record) adı verilmektedir.*
- [veri/veri_thinkStats2_2002FemPreg.dct](../../../veri/veri_thinkStats2_2002FemPreg.dct) dosyası da veri dosyasının "dictionary" formatındaki halidir. Kabaca söylemek gerekirse verinin açıklamalarını içermektedir. Bu ve bunun gibi dict dosyaları ileride kullanılacaktır.

::: {.callout-caution}
Bu kitapta kullanılan fonksiyonlardan bir class oluşturulmuştur.** Ancak kod kısmı eski olduğu için bazı kısımlarını yenileyeceğiz ve kendimiz yazacağız.
:::

## Data Çerçeveleri

Bu kitapta `pandas` paketi ile hazır olarak yazılmış fonksiyonlar kullanılarak yeni fonksiyonlar/class'lar tanımlanmıştır.

### Değişkenler

[veri/veri_thinkStats2_2002FemPreg.dct](../../../veri/veri_thinkStats2_2002FemPreg.dct) dosyası içerisinde 244 adet değişken vardır. Kitapta kullanılacak olan bazıları şunlardır:

- `caseid`: Her bir kayıt (respondent) için bir benzersiz numara.
- `prglngth`: Hamilelik süresi (hafta)
- `outcome`: Doğum sonucu (1= sağlıklı doğum)
- `pregordr`: Hamilelik sırası veya seri numarası: İlk hamilelik için 1, ikinci hamilelik için 2, vb.
- `birthord`: Sağlıklı doğan çocuğun seri numarası: İlk doğan için 1, ikinci doğan için 2, vb.
- `birthwgt_lb` ve `birthwgt_oz`: Doğum ağırlığı (pound) ve ağırlığın ons kısmı. 
  - 1 oz = 28.34952 g (Ounce)
  - 1 lb = 0.45359237 kg (Pound)
- `agepreg`: Hamilelikteki yaş (yıl)
- `finalwgt`: Her bir kayıt için ağırlıklandırılmış (weighted) nüfus sayısı. Bu ağırlıklandırma, Amerika'daki nüfusun dağılımını yansıtmaktadır.

## `thinkstats2` Modülü

Bu bölümde *başkasının* yazdığı `thinkstats2` modülünü kullanacağız. Bu modülün içeriğine [bu linkten](thinkStats2/) erişebilirsiniz.

## Kaynaklar

1. [Think Stats: Probability and Statistics for Programmers, Allen B. Downey, Franklin W. Olin, Green Tea Press, 2014](https://greenteapress.com/thinkstats2/thinkstats2.pdf)
2. [Think Stats: Github](https://github.com/AllenDowney/ThinkStats2)