---
title: "SDP - Atış Yöntemi"
---

## Adi Diferansiyel Denklemler

Aşağıdaki gibi bir adet diferansiyel denklem veya denklem sistemimiz olsun.

$$
\begin{equation}
    \frac{d}{dx}y(x) = F(x,y)
\end{equation}
$$

- Bu denklemi çözmek demek sağ ve sol tarafın integralini almak demektir.
- Bu denklemi çözmek demek *sayısal* olarak $y(x)$ fonksiyonunu bulmak demektir. Yani istenilen bir x değeri için $y(x)$ fonksiyonunun değerini elde ederiz.
- $y(x)$ ve $F(x,y)$ birer vektör olabilir. Örneğin $\vec{y}(x) = (y_{1}(x), y_{2}(x))$.
- İkinci dereceden diferansiyel denklemleri çözmek için denklemi iki adet birinci dereceden diferansiyel denkleme indirgeme yapmamız gerekmektedir.

$$
\begin{align*}
    \frac{d^{2}}{dx^{2}}y(x) =& F(x,y)\\
    \frac{d}{dx}y(x) =& v(x,y) \qquad \text{ve} \qquad \frac{d}{dx}v(x) = F(x,y)
\end{align*}
$$

1. Çözüme başlamak için fonksiyonun başlangıçtaki değerine ihtiyacınız vardır; **Başlangıç Değer Problemi, BDP (IVP)**
2. Çözümün sınırlarında hangi değerler aldığını bilerek de fonksiyonu elde edebiliriz; **Sınır Değer Problemi, SDP (BVP)**

**Örneğin**

- Başlangıç değer problemi:

$$
y''(x)= -y, \qquad y(0)=1, \qquad y'(0)=0 \text{.}
$$

- Sınır değer problemi:

$$
y''(x)= -y, \qquad y(0)=1, \qquad y'(\pi)=0 \text{.}
$$

## Sınır Değer Problemi

- Farz edelim ki aşağıdaki gibi ikinci dereceden diferansiyel denklemimiz olsun.

$$
y''(x) = f(x,y,y')
$$

- Bu denklemdeki $y(x)$ ve $y'(x)$ fonksiyonunun aynı $x$ (ör. $x=0$) noktasındaki değerini biliyorsak bu denklem başlangıç değer problemidir.
- Bu denklemin $y(x=a)$ ve $y(x=b)$ noktalarındaki değerlerini biliyorsak bu denklem **sınır değer problemidir.**
- Yukarıda verdiğimiz örneğe iki-noktalı sınır değer problemi de denir (2-point boundary value problem).
- Birinci dereceden diferansiyel denklem için sınır değer problemi ile başlangıç değer problemi aynıdır, çünkü denklem bir adet koşula sahiptir.

**Örneğin** Kuyudaki bir parçacığın hareket denklemi aşağıdaki gibi yazılır.

$$
\frac{-h}{4\pi m}\frac{d^{2}}{dx^{2}}\psi(x) = E\psi(x), \qquad \psi(x=-L/2)=0, \qquad \psi(x=L/2)=0 \text{.}
$$

Birinci türeve ait bir koşul bilmiyoruz. Sadece bulmak istediğimiz fonksiyonun sınır değerlerini biliyoruz.

::: {.callout-warning}
Başlangıç değer probleminde n. dereceden diferansiyel denklemi çözebilmek için n adet başlangıç koşuluna ihtiyaç vardır. Bu başlangıç koşulları da (n-1). dereceden türeve kadar olmak zorundadır.
:::

- Sınır değer problemlerini çözmek için birinci türeve ait olan denklemdeki başlangıç koşuluna ihtiyaç vardır. Bu sorunu:
  1. Başlangıç koşulunu <span style="color:red"> tahmin ederek </span> aşabiliriz. Bu yönteme *atış yöntemi* (shooting method) denir.
  2. Diferansiyel denklemi <span style="color:red"> örgü noktalarına </span> (mesh points) bölerek çözebiliriz. Bu yönteme *sonlu farklar yöntemi* (finite difference method) denir.

### Atış Yöntemi

Aşağıdaki denklemi çözelim.

$$
y'' = f(x,y,y'), \qquad y(a)=\alpha, \qquad y(b)=\beta \text{.}
$$

- Bu denklemi başlangıç değer problemine çevirmeye çalışalım.

$$
y'' = f(x,y,y'), \qquad y(a)=\alpha, \qquad y'(a)=u \text{.}
$$

- $u$ nedir? Tahmin edeceğiz. Buradan dif. denklemi tıpkı başlangıç değer problemi gibi $a$'dan $b$'ye kadar çözeceğiz.
- Bulduğumuz çözümün son noktasındaki değerde yani $y_{cozum}(b)$,  $\beta$'yu bulana kadar bu işleme devam edeceğiz.
- Sistematik bir tahmin yürütme mekanizması kurmamız lazım. Bunun için $y(b)$, $u$'nun bir fonksiyonu olsun tanımlaması yapalım.

$$
y(b)= \theta(u) \text{.}
$$

Buradan $u$ değerini bulmak için yukarıda verilen denklemin kökünü bulmamız lazım.

$$
\theta(u)- \beta \equiv r(u) = 0 \text{.}
$$

Buradaki $r(u)$ fonksiyonuna *artık fonksiyon* (residual function) denir. Bu fonksiyonun kökü $u$ değeridir. $u$ değerini biliyorsak sınır değer probleminden çevirdiğimiz başlangıç değer problemini çözebiliriz.

- **Artık fonksiyonunun kökü** $u$ değerini verecek. Kök bulmak için *Ridder'in yöntemi* kullanabiliriz. (Bisection veya Newton-Raphson yöntemleri değil.)


**Çözüme giden adımları** tekrar yazalım.

1. İkinci dereceden diferansiyel denklemimiz var. $y''=f(x,y,y')$.
2. Çözüm kümesinin sınır değerlerini biliyoruz. $y(a)=\alpha$, $y(b)=\beta$.
3. Bizim çözebildiğimiz denklem tipinde başlangıç koşulları $y(a)=\alpha$ ve $y'(a)=u$ şeklinde olmalı.
4. $u$ değerini tahmin edelim.
5. Tahmin ettiğimiz $u$ değerini kullanarak $y''=f(x,y,y')$ denklemini $b$ noktasına kadar çözelim.
6. Elde ettiğimiz çözümün $b$'deki değeri $y(b)=\beta$ değerini veriyor mu? Eğer vermiyorsa $u$ değerini değiştirerek tekrar deneyelim.
7. $u$'nun bu değişimi sanki bir fonksiyon gibi olsun. Yukarıda bahsettiğimiz $\theta(u)$ fonksiyonu budur.
8. $\theta(u)$ fonksiyonu $\beta$'ya eşit olursa $u$ değerini bulduk demektir. Yani $\theta(u)- \beta = 0$ denkleminin kökünü bulmaya çalışıyoruz.
9. $y(b)=\beta$ değerine *yeteri kadar* yaklaştı ise $u$ değerini yani başlangıç koşulunu yani $y(x)$ fonksiyonunu bulduk demektir.
10. Denklem çözüldü.

## Alıştırma 1

Aşağıda verilen difarensiyel denklemi atış yöntemi ile çözelim.
$$
y''(t) = -g, \qquad y(0)=0, \qquad y(5)=50 \text{.}
$$

### Çözüm

- Çözüm adımlarından dördüncü olan ile başlayalım. $u$ değerini tahmin edelim. $u=25$ olsun. Bu değerle denklemi çözelim. Çözeceğimiz denklem aşağıdaki gibi olacak.

$$
y''(t) = -g, \qquad y(0)=0, \qquad y'(5)=25 \text{.}
$$

Bu denklemin çözümü 

$$
y'(t)= -gt + C_{1} \text{,} \qquad y'(5)=25 \text{.}
$$

$$
y'(t)= -gt + 25 \text{,} \qquad y(x)=-\frac{gt^2}{2} + 25t + C_{2} \text{.}
$$

$$
y(t)=-\frac{gt^2}{2} + 25t
$$

Şimdi tahminimiz doğru mu deneyelim. 

$$
y(t=5)= -\frac{10\times 25}{2} + 25\times 5 = 0 \ne 50 \text{.}
$$

Yanlış! Farklı bir $u$ değeri almamız gerekecek. Aynı işlemi $u=40$ ile tekrarlayalım. Sonuç:

$$
y(t)=-\frac{gt^2}{2} + 40t
$$

Olacak denersek eğer $y(5)=75$ olacak ve yanlış olacak.

Teker teker denemek yerine $u$ değeri sanki bir fonksiyonmuş gibi davranalım.

$$
\theta(u) - 50 = 0\text{.}
$$

O halde $\theta(u)$ fonksiyonu başlangıç değer probleminin çözümüne bağlı. Bunu bir fonksiyon gibi tanımlayıp kökünü bulalım.

```{python}
import numpy as np
import matplotlib.pyplot as plt
import scipy.integrate as scInteg
import scipy.optimize as scOpt

# Diff. Denk:
# y'' = -10 , y(0)=0 , y(5)=50

# f(x,y,y') = -10
# y' = v   => f1= v
# v' = -10 => f2= -10

# Fonksiyon:
def fonk_SDP(t, y):
    # y[0]= y
    # y[1]= v
    return np.array([y[1], -10])

# Başlangıç Koşulları:
t0=0.
tStop=5.
y0= 0.     # y(0) = 0
yStop= 50. # y(5) = 50
# v(0) = u (Bilmiyoruz)

# Hangi Aralıkta Çözeceğiz: t0'dan tStop'e kadar

# Theta fonksiyonu:
def thetaFonk(u):
    #solve_ivp(fonksiyon, t_span, y0)
    # t_span=[t0, tStop] (y(0) ve y(1) değerini biliyoruz.)
    cozum = scInteg.solve_ivp(fonk_SDP, [t0, tStop], [y0, u])
    
    # Bizim için önemli olan y(1) değeri, v'nin değil.
    # yani y'nin y(1) değerinin 
    yCozum = cozum.y[0]
    return yCozum[-1]- yStop

# Theta fonksiyonunun içerini şöyle düşünelim.
# Polinom tipi bir g(x)=x^2+4x+4 fonksiyonu olsun. Bunun kökünü şöyle bulurduk.
'''
def g(x):
    return x**2 + 4*x + 4

# Kökünü 0 ile 10 arasında bul.
x0, = scOpt.ridder(g, 0, 10)
'''
# Aynı şekilde theta fonksiyonunun kökünü bulalım.
thetaU_kok_v0= scOpt.ridder(thetaFonk, 0, 50)

# Olması gereken başlangıç değeri:
print(f"v0= {thetaU_kok_v0} m/s")

# Deneyelim. Gerçekten v0 bu değerdeyken y(5)= 50 oluyor mu?

cozum= scInteg.solve_ivp(fonk_SDP, [t0, tStop], [y0, thetaU_kok_v0])

print(f"y(5)= {cozum.y[0][-1]} m")
```

Python ile ne yaptık?

1. Sanki başlangıç değer problemi çözer gibi fonksiyon tanımladık.
2. Başlangıç koşullarını tanımladık. İkinci başlangıç değeri yani $y(b)$ değerini tanımlamadık. 
3. Ayrı bir fonksiyon ile başlangıç değer problemini çözdük. Bu fonksiyonun girdi değeri `u`, dönüş dğeri ise verilen $y(b)$ değeri ile çözümün son değerinin farkıdır.
4. Başlangıç değer çözücü denklemi `scipy.optimize.ridder(fonksiyon, kok_araligi_baslangic, kok_araligi_bitis)` ile çözdük.

## Problemler

### Problem 1

Aşağıdaki denklemi atış yöntemi ile çözün.

$$
y''(t)=t, \quad y(0)=1, \quad y(3)=9
$$

1. Elde ettiğiniz çözümü yani $y(t)$ fonksiyonunu çizdirin.
2. Bu denklemi analitik olarak çözün ve çözümü de çizdirin.

## Referanslar

1. Numerical Methods in Engineering with Python 3, Jaan Kiusalaas, Cambridge University Press, 2013, **Syf:293**
2. Python Programming and Numerical Methods: A Guide for Engineers and Scientists, Qingkai Kong & Timmy Siauw & Alexandre Bayen, 2020, [chapter23.02-The-Shooting-Method](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter23.02-The-Shooting-Method.html)